name: acceptance-testing

on:
  # this will allow to run test on main and not modify the status badge when opening a PR
  push:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  trigger-code-pipeline:
    runs-on: ubuntu-latest
    name: Trigger AWS CodePipeline
    environment: acceptance
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-east-2
          role-duration-seconds: 3600
          role-session-name: GithubActions-Session

      - name: Run AWS Pipeline
        run: |
          echo "Triggering AWS Pipeline"
          PIPELINE_EXECUTION_ID=(aws codepipeline start-pipeline-execution --name ${{ secrets.PIPELINE_NAME }} \
            --region us-east-2 \
            --variables GithubUser=${{ github.repository_owner }},GithubBranch=${{ github.ref_name }} \
            --output text \
            --query 'pipelineExecutionId')
      - name: Wait for AWS Pipeline to complete
        run: |
          while true; do
            STATUS=$(aws codepipeline get-pipeline-execution --pipeline-name ${{ secrets.PIPELINE_NAME }} --pipeline-execution-id $PIPELINE_EXECUTION_ID --region us-east-2 | jq -r '.pipelineExecution.status')
            if [ "$STATUS" = "Succeeded" ]; then
              echo "Pipeline execution succeeded"
              break
            elif [ "$STATUS" = "Failed" ]; then
              echo "Pipeline execution failed"
              exit 1
            fi
            sleep 10
          done
