name: acceptance-testing

on:
  # this will allow to run test on main and not modify the status badge when opening a PR
  push:

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  trigger-code-pipeline:
    runs-on: ubuntu-latest
    name: Trigger AWS CodePipeline
    environment: acceptance
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-east-2
          role-duration-seconds: 3600
          role-session-name: GithubActions-Session

      - name: Run AWS Pipeline
        run: |
          echo "Triggering AWS Pipeline"
          PIPELINE_EXEC_ID=$(aws codepipeline start-pipeline-execution --name ${{ secrets.PIPELINE_NAME }} \
            --region us-east-2 \
            --variables name=GithubUser,value=${{ github.repository_owner }} name=GithubBranch,value=${{ github.ref_name }} \
            --output text \
            --query 'pipelineExecutionId')
          ./.github/workflows/monitor_pipelines.sh $PIPELINE_EXEC_ID
