name: acceptance-testing

on:
  # this will allow to run test on main and not modify the status badge when opening a PR
  push:
  workflow_dispatch:
    inputs:
      pipeline:
        description: "CodePipeline pipeline name"
        type: string
        default: "dummy"
        required: true

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: false

jobs:
  trigger-code-pipeline:
    runs-on: ubuntu-latest
    name: Trigger AWS CodePipeline
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v2
        if: steps.changes.outputs.src== 'true'
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-west-2
          role-duration-seconds: 3600
          role-session-name: GithubActions-Session

      - name: Run AWS Pipeline
        run: |
          echo "Triggering AWS Pipeline"
          if [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
            aws codepipeline start-pipeline-execution --name ${{ inputs.pipeline }} --region us-west-2
          fi
